## Exercícios aula 2 _ Numpy - Alessandra

In [2]:
## EXE 01 - Usando NumPy, importe o dataset iris mantendo o seu conteúdo intacto.

import numpy as np

iris_dataset_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
colunas = ('sepallenghth', 'sapalwidth', 'petallength', 'petalwidth', 'species')

iris = np.genfromtxt(iris_dataset_url, delimiter=',', dtype='object', encoding='ascii')

#print(iris [:15,4])

#Definir as ordens das colunas no vetor e os tipos de cada variável
sepallenghth = iris[:, 0].astype(float)
sapalwidth = iris[:, 1].astype(float)
petallength = iris[:, 2].astype(float)
petalwidth = iris[:, 3].astype(float)
species = iris[:, 4].astype(str)


In [13]:
## EXE 02 - Extraia a coluna species do dataset importado na questão anterior para um vetor unidimensional.

species = iris[:, 4].astype(str)
print(species)

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor

In [14]:
## EXE 03 - Calcule a média, mediana e desvio padrão da primeira coluna (sepallength) do dataset Iris.

media_sepallenghth = sepallenghth.mean()
mediana_sepallenghth = np.median(sepallenghth)
desvpad_sepallenghth = sepallenghth.std()

print('Média: {}'.format(media_sepallenghth))
print('Mediana: {}'.format(mediana_sepallenghth))
print('Desvio Padrão: {}'.format(desvpad_sepallenghth))

Média: 5.843333333333334
Mediana: 5.8
Desvio Padrão: 0.8253012917851409


In [3]:
## EXE 04 - Normalize a coluna (sepallength) do dataset iris de tal forma que o valor
## mínimo seja zero (0) e o valor máximo seja 1.

sepallenghth_max = sepallenghth.max()
sepallenghth_min = sepallenghth.min()

sepallenghth_normalize = ( sepallenghth - sepallenghth_min ) / (sepallenghth_max - sepallenghth_min)

print(sepallenghth[:3])
print(sepallenghth_normalize[:3])

4.3
[5.1 4.9 4.7]
[0.22222222 0.16666667 0.11111111]


In [21]:
## EXE 05 - Encontre o 5º e o 95º percentil do comprimento das pétalas (sepallength) do dataset Iris.

np.percentile(sepallenghth, q=[5, 95])

array([4.6  , 7.255])

In [4]:
## EXE 06 - 

#Encontre a quantidade de valores ausentes, bem como a posição deles da primeira coluna da 
#coluna comprimento das pétalas (sepallength), dentro do vetor abaixo:

iris_2d = np.genfromtxt(iris_dataset_url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan


print('Quantidade de Valores Ausentes:', np.isnan(iris_2d[:, 0]).sum())
print('Quantidade de Valores Ausentes:',np.where(np.isnan(iris_2d[:, 0])))


Quantidade de Valores Ausentes: 9
Quantidade de Valores Ausentes: (array([  0,   4,   7,  35,  38,  48,  85,  92, 134], dtype=int64),)


In [4]:
## EXE 07 - Filtre o vetor iris_2d do exercício anterior para que ele tenha:
#(terceira coluna (petallength) > 1.5) && (primeira coluna (sepallength) < 5.0)

iris_2d = np.genfromtxt(iris_dataset_url, delimiter=',', dtype='float', usecols=[0,1,2,3,4])

coluna_filtrada = (iris_2d[:, 2]> 1.5) & (iris_2d[:, 0] < 5.0)
iris_2d[coluna_filtrada]

array([[4.8, 3.4, 1.6, 0.2, nan],
       [4.8, 3.4, 1.9, 0.2, nan],
       [4.7, 3.2, 1.6, 0.2, nan],
       [4.8, 3.1, 1.6, 0.2, nan],
       [4.9, 2.4, 3.3, 1. , nan],
       [4.9, 2.5, 4.5, 1.7, nan]])

In [4]:
## EXE 08 - Selecione as linhas do vetor iris_2d que não contenham valores nan (Not a Number).

iris_2d = np.genfromtxt(iris_dataset_url, delimiter=',', dtype='float', usecols=[0,1,2,3])

any_nan_in_row = np.array([~np.array(np.isnan(row)) for row in iris_2d])
iris_2d[any_nan_in_row][:5]

#np.isnan(iris_2d).any()

array([5.1, 3.5, 1.4, 0.2, 4.9])

In [35]:
## EXE 09 - Encontre a correlação entre a primeira coluna (sepallength) e a (terceira coluna (petallength) no vetor iris_2d.

np.corrcoef(iris_2d[:, 0], iris_2d[:, 2])

array([[1.        , 0.87175416],
       [0.87175416, 1.        ]])

In [3]:
## EXE 10 - Verifique se o vetor iris_2d possui qualquer valor faltante,
# caso possui deverá retornar True caso contrário False.

iris_2d = np.genfromtxt(iris_dataset_url, delimiter=',', dtype='float', usecols=[0,1,2,3,4])

np.isnan(iris_2d).any()

True

In [7]:
## EXE 11 - Substitua todas as ocorrências de nan (Not a Number) por zeros em um vetor NumPy.

iris_2d = np.genfromtxt(iris_dataset_url, delimiter=',', dtype='float', usecols=[0,1,2,3])

iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

iris_2d[np.isnan(iris_2d)] = 0

iris_2d[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 0. , 1.4, 0.2],
       [0. , 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [5]:
## EX 12 - Encontre e conte os valores únicos da coluna species

iris_2d = np.genfromtxt(iris_dataset_url, delimiter=',', dtype='object', usecols=[4])

np.unique(iris_2d, return_counts=True)

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype=object), array([50, 50, 50], dtype=int64))

In [10]:
## EXE 13 - Mapeie terceira coluna (petallength)(, 2) de tal forma que os valores numéricos sejam substituídos 
# por valores textuais, seguindo de acordo com a tabela abaixo:

iris = np.genfromtxt(iris_dataset_url, delimiter=',', dtype='object')

intervalo = np.digitize(iris[:, 2].astype('float'), [0, 3, 5, 10])
mapeamento = {1: 'pequeno', 2:'médio', 3:'grande', 4: np.nan}
classificacao = [mapeamento[valor] for valor in intervalo]

print(classificacao)

['pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'pequeno', 'médio', 'médio', 'médio', 'médio', 'médio', 'médio', 'médio', 'médio', 'médio', 'médio', 'médio', 'médio', 'médio', 'médio', 'médio', 'médio', 'médio', 'médio', 'médio', 'médio', 'médio', 'médio', 'médio', 'médio', 'médio', 'médio', 'médio', 'grande', 'médio', 'médio', 'médio', 'médio', 'médio', 'grande', 'médio', 'médio', 'médio', 'médio', 'médio', 'médio', 'médio', 'médio', 'médio', 'médio', 'médio', 'médio', 'médio', 'médio', 'médio', 'médio

In [20]:
## EXE 14 - Crie uma nova coluna chamada volume, preenchida com dados resultantes da seguinte equação:

# 𝑣𝑜𝑙𝑢𝑚𝑒 = ( 𝑃𝑖 𝑥 𝑃𝑒𝑡𝑎𝑙𝑙𝑒𝑛𝑔𝑡ℎ 𝑥 𝑆𝑒𝑝𝑎𝑙𝐿𝑒𝑛𝑔𝑡ℎ2 ) / 3

iris = np.genfromtxt(iris_dataset_url, delimiter=',', dtype='object')

# Calular o volume
sepallenghth = iris[:, 0].astype('float')
petallength = iris[:, 2].astype('float')
volume = (np.pi * petallength * (sepallenghth ** 2)) / 3

# Criar nova dimensão
volume = volume[:, np.newaxis]

# Adiciona um nova coluna com a dimensão criada
saida = np.hstack([iris, volume])

print(saida[:5])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa' 38.13265162927291]
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa' 35.200498485922445]
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa' 30.0723720777127]
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa' 33.238050274980004]
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa' 36.65191429188092]]


In [27]:
## EXE 15 - Usando NumPy e o dataset iris responda:
# Qual é o segundo maior valor de comprimento de pétala (petallength) da espécie setosa?

iris = np.genfromtxt(iris_dataset_url, delimiter=',', dtype='object')

iris2 = iris[iris[:, 2].argsort()]

petallength2 = iris2[:, 2].astype(float)

local = len(petallength2)-2

print(petallength2[local])


6.7


In [30]:
## EXE 16 - Ordene o dataset iris com base na coluna sepallength de maneira crescente.

iris = np.genfromtxt(iris_dataset_url, delimiter=',', dtype='object')

print(iris[iris[:, 0].argsort()][:10])


[[b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'4.4' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'3.0' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.5' b'2.3' b'1.3' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.6' b'1.0' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.2' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']]


In [109]:
## EXE 17 - Encontre o valor mais frequente da terceira coluna (petallength) do dataset iris.

iris = np.genfromtxt(iris_dataset_url, delimiter=',', dtype='object')

valores, contagem = np.unique(iris[:, 2], return_counts = True)
print(valores)
print(contagem)
valores[np.argmax(contagem)]

[b'1.0' b'1.1' b'1.2' b'1.3' b'1.4' b'1.5' b'1.6' b'1.7' b'1.9' b'3.0'
 b'3.3' b'3.5' b'3.6' b'3.7' b'3.8' b'3.9' b'4.0' b'4.1' b'4.2' b'4.3'
 b'4.4' b'4.5' b'4.6' b'4.7' b'4.8' b'4.9' b'5.0' b'5.1' b'5.2' b'5.3'
 b'5.4' b'5.5' b'5.6' b'5.7' b'5.8' b'5.9' b'6.0' b'6.1' b'6.3' b'6.4'
 b'6.6' b'6.7' b'6.9']
[ 1  1  2  7 12 14  7  4  2  1  2  2  1  1  1  3  5  3  4  2  4  8  3  5
  4  5  4  8  2  2  2  3  6  3  3  2  2  3  1  1  1  2  1]


b'1.5'

In [32]:
## EXE 18 - Encontre a posição da primeira ocorrência de um valor maior do que 1.0
# da quarta coluna (petalwidth) do dataset iris.

iris = np.genfromtxt(iris_dataset_url, delimiter=',', dtype='object')

np.argwhere(iris[:, 3].astype('float') > 1.0)[0]


array([50], dtype=int64)

In [34]:
## EXE 19 - Obtenha a posição dos top 5 valores maxímos do vetor abaixo:

#Solução Alessandra
np.random.seed(100)
vetor = np.random.uniform(1,50, 20)

vetor2 = vetor[vetor.argsort()]

print(vetor)

parametro = vetor2[len(vetor) - 6]

print(parametro)

print(np.argwhere(vetor.astype('float') > parametro))

#outra solução apresentada pelo professor
np.argpartition(-vetor, 5)[:5]

[27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]
40.77247430537684
[[ 3]
 [ 7]
 [10]
 [15]
 [18]]


array([15, 10,  3,  7, 18], dtype=int64)

In [5]:
## EXE 20 - Encontre a média de uma coluna numérica agrupada por uma coluna categórica em uma matriz (vetor numpy 2D)

iris = np.genfromtxt(iris_dataset_url, delimiter=',', dtype='object')
colunas = ('sepallenghth', 'sapalwidth', 'petallength', 'petalwidth', 'species')

coluna_numerica = iris[:, 1].astype('float')
coluna_categorica = iris[:, 4]

saida = []

for categoria in np.unique(coluna_categorica):
    saida.append([categoria, coluna_numerica[coluna_categorica == categoria].mean()])

saida

[[b'Iris-setosa', 3.418],
 [b'Iris-versicolor', 2.7700000000000005],
 [b'Iris-virginica', 2.974]]